export const GET_ALL_AIRPLANE_PENDING = 'GET_ALL_AIRPLANE_PENDING';
export const GET_ALL_AIRPLANE_COMPLETE = 'GET_ALL_AIRPLANE_COMPLETE';
export const GET_ALL_AIRPLANE_REJECTED = 'GET_ALL_AIRPLANE_REJECTED';

export const ADD_AIRPLANE_PENDING = 'ADD_AIRPLANE_PENDING';
export const ADD_AIRPLANE_COMPLETE = 'ADD_AIRPLANE_COMPLETE';
export const ADD_AIRPLANE_REJECTED = 'ADD_AIRPLANE_REJECTED';

export const REMOVE_AIRPLANE_PENDING  = 'REMOVE_AIRPLANE_PENDING';
export const REMOVE_AIRPLANE_COMPLETE = 'REMOVE_AIRPLANE_COMPLETE';
export const REMOVE_AIRPLANE_REJECTED = 'REMOVE_AIRPLANE_REJECTED';

export const GET_AIRPLANE_POSITION_RESPONSE = 'GET_AIRPLANE_POSITION_RESPONSE';